### ISSUE TITLE
Support Spaces in file names

### ISSUE THREAD

**Issue by Andre601** [Decathlon/wiki-page-creator-action#7]
When you have files/pages that contain spaces (e.g `configure bot.md`) does the action treat those as separate pages and errors with the following message(s):
```
cp: can't stat 'wiki/configure.md': No such file or directory
```

The action should support spaces by f.e. replacing them with dashes (-).

**Comment by didnotwant** [comment]
Putting spaces in filenames is not a good practice, though.

I edited my comment because I thought that your problem is similar to mine but it’s not.
But what’s related to your problem is that in this repo I could find a pull request (#10) which added a support for converting underscores `_` to spaces in sidebar.

<hr />

Let me connect to your thread because I think it’s not worth creating yet another one:

I have no clue why hyphens are converted to spaces in the sidebar:
e.g. filename "How-to-use.md" results in "How to use" on the list:
![image](https://user-images.githubusercontent.com/13979371/80212985-c636eb80-8638-11ea-8a1f-3700f56ea468.png)

@mmornati — do you have any knowledge on this?

For now the best approach I can choose to not rely on the filename in the sidebar is to create a [custom sidebar](https://help.github.com/en/github/building-a-strong-community/creating-a-footer-or-sidebar-for-your-wiki#creating-a-footer-or-sidebar-locally).

**Comment by mmornati** [comment]
@didnotwant It is by design in GitHub wiki pages I guess: in the wiki the `-` are automatically converted in spaces.

**Comment by mmornati** [comment]
@Andre601 I think I can try to fix problem allowing the action to take care to file with spaces... but I'm not sure what is then the result in GitHub.
